### ISSUE TITLE
ADC Clip Voltage Distinction Based on Resistors

### ISSUE THREAD

**Issue by KushalP17** [delta-12/LaserTag#68]

**Comment by delta-12** [comment]
@KushalP17 Please update your local copy of the branch associated with this issue.  I merged my recent changes into it since they have not been merged into `develop` yet.

**Comment by delta-12** [comment]
@KushalP17 I'm thinking the ADC code should either go under the existing `Gpio` module or in its own module under `LaserBlaster/main`, following the format of the other modules in that directory.  The code itself should also be formatted similarly to the code in modules such as `Gpio`, `BopItCommands`, and `EventHandlers`.

**Comment by delta-12** [comment]
@KushalP17 This issue will be resolved in the PR for #80 .  The branch for this issue will be deleted and any other necessary work for this issue should be completed on the branch for #80 .
